repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: pipenv run isort
        language: python
        files: \.py$
        args: ["-w", "120", "-m", "3"]
    -   id: black
        name: black
        entry: pipenv run black .
        language: python
        files: \.py$
        args: [ "-l", "120" ]
        pass_filenames: false
    -   id: autoflake
        name: autoflake
        entry: pipenv run autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]
        files: ^recsys/|tests/
    -   id: flake8
        name: flake8
        entry: pipenv run flake8
        language: python
        pass_filenames: false
        args: ['--ignore=E501']
    -   id: mypy
        name: mypy
        entry: pipenv run mypy
        language: python
        'types': [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []
